# Generated by Django 5.1.7 on 2025-05-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Страна"
            ),
        ),
    ]
