# Generated by Django 5.1.7 on 2025-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
